### PR TITLE
Auth

### PR DESCRIPTION
**Pull request by darshandamre**
created signup, login and logout features
have used typescript

review the components in `src/features/auth/` folder 
ignore `src/app/api/generated/graphql.ts` file as this is an auto generated file using graphql-codegen,
you can also choose to ignore graphql queries.

PS: the homepage is empty so use the navbar to navigate to signup/login pages, the server might be little slow so please have some patience while testing the ui.
[Preview deploy](https://social-media-git-auth-rebased-darshandamre.vercel.app/)

### CODE REVIEW

**Comment by anandsr21harshit** [comment]
-loved the transition in input box. 👏👏
- routes are working fine

**Review by anandsr21harshit — APPROVED** [review]
you can merge this PR

**Comment by darshandamre** [comment]
> -loved the transition in input box. 👏👏
> 
> * routes are working fine

thanks to material ui

**Review by sashaboi — APPROVED** [review]
created an account ,everything looks amazing. 

looking forward to more.

**Pull request merged**
